# Generated by Django 5.2.5 on 2025-08-21 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, verbose_name="이름"),
                ),
                (
                    "교육수준분류",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "고등학교 중퇴 이하"),
                            (2, "고등학교 졸업"),
                            (3, "대학교 중퇴/전문대 졸업"),
                            (4, "대학교 졸업 이상"),
                        ],
                        null=True,
                        verbose_name="교육수준",
                    ),
                ),
                (
                    "연령대분류",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "18-25세"),
                            (2, "26-35세"),
                            (3, "36-45세"),
                            (4, "46-55세"),
                            (5, "56-65세"),
                            (6, "66세 이상"),
                        ],
                        null=True,
                        verbose_name="연령대",
                    ),
                ),
                (
                    "가구주성별",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "남성"), (2, "여성")],
                        null=True,
                        verbose_name="성별",
                    ),
                ),
                (
                    "결혼상태",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "기혼"), (2, "미혼/기타")],
                        null=True,
                        verbose_name="결혼상태",
                    ),
                ),
                (
                    "저축여부",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "저축 안함"), (2, "일부 저축"), (3, "적극적 저축")],
                        null=True,
                        verbose_name="저축습관",
                    ),
                ),
                (
                    "직업분류1",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "일반 직장인/중간관리직"),
                            (2, "고소득 전문직/사업가/경영진"),
                            (3, "은퇴자/연금수급자"),
                            (4, "저소득층/학생/비정규직"),
                        ],
                        null=True,
                        verbose_name="직업분류",
                    ),
                ),
                (
                    "금융위험감수",
                    models.BooleanField(default=False, verbose_name="투자 위험 감수 의향"),
                ),
                ("금융위험회피", models.BooleanField(default=False, verbose_name="안전 투자 선호")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필",
            },
        ),
    ]
