# Generated by Django 5.2.5 on 2025-08-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="금융위험감수",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="금융위험회피",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="금융위험태도",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="금융위험태도"
            ),
        ),
    ]
