# Generated by Django 5.2.5 on 2025-08-20 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("link", models.URLField(max_length=1000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("주식/증권", "주식/증권"),
                            ("채권", "채권"),
                            ("금리", "금리"),
                            ("환율/외환", "환율/외환"),
                            ("부동산", "부동산"),
                            ("은행/대출", "은행/대출"),
                            ("보험/연금", "보험/연금"),
                            ("투자/자산관리", "투자/자산관리"),
                            ("경제지표", "경제지표"),
                            ("정책/규제", "정책/규제"),
                            ("기타금융", "기타금융"),
                        ],
                        default="기타금융",
                        max_length=50,
                    ),
                ),
                ("source", models.CharField(default="네이버 뉴스", max_length=100)),
                ("pub_date", models.CharField(max_length=20)),
                (
                    "collected_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-collected_time"],
                "unique_together": {("title", "link")},
            },
        ),
    ]
